version: '3.8'
services:
  app:
    build:
      context: .
    ports:
      - ${APP_PORT}:9000
    restart: on-failure
    container_name: api_articles_app
    volumes:
      - .:/app
    environment:
      - API_ADDRESS=:9000
      - DATA_SOURCE_NAME=${DB_USER}:${DB_PASSWORD}@tcp(db:3306)/${DB_NAME}?charset=utf8mb4&parseTime=True
      - REDIS_ADDRESS=cache:6379
      - WAIT_HOSTS=db:3306,cache:6379
    env_file:
      - ./.env
    depends_on:
      - db
      - cache
    links:
      - db
      - cache
  db:
    image: mysql:8.1.0
    container_name: mysql_articles_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - db:/var/lib/mysql
  cache:
    image: redis:6.2-alpine
    container_name: redis_articles_cache
    restart: always
    ports:
      - '${REDIS_PORT}:6379'
    command: redis-server
    volumes:
      - cache:/data
volumes:
  db:
    driver: local
  cache:
    driver: local
