// Code generated by MockGen. DO NOT EDIT.
// Source: articles.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/dewzzjr/ais/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockArticle is a mock of Article interface.
type MockArticle struct {
	ctrl     *gomock.Controller
	recorder *MockArticleMockRecorder
}

// MockArticleMockRecorder is the mock recorder for MockArticle.
type MockArticleMockRecorder struct {
	mock *MockArticle
}

// NewMockArticle creates a new mock instance.
func NewMockArticle(ctrl *gomock.Controller) *MockArticle {
	mock := &MockArticle{ctrl: ctrl}
	mock.recorder = &MockArticleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArticle) EXPECT() *MockArticleMockRecorder {
	return m.recorder
}

// FetchArticles mocks base method.
func (m *MockArticle) FetchArticles(arg0 context.Context, arg1 model.Filter) ([]model.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchArticles", arg0, arg1)
	ret0, _ := ret[0].([]model.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchArticles indicates an expected call of FetchArticles.
func (mr *MockArticleMockRecorder) FetchArticles(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchArticles", reflect.TypeOf((*MockArticle)(nil).FetchArticles), arg0, arg1)
}

// GetArticlesByID mocks base method.
func (m *MockArticle) GetArticlesByID(arg0 context.Context, arg1 ...int64) ([]model.Article, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetArticlesByID", varargs...)
	ret0, _ := ret[0].([]model.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArticlesByID indicates an expected call of GetArticlesByID.
func (mr *MockArticleMockRecorder) GetArticlesByID(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticlesByID", reflect.TypeOf((*MockArticle)(nil).GetArticlesByID), varargs...)
}

// InsertArticle mocks base method.
func (m *MockArticle) InsertArticle(arg0 context.Context, arg1 model.Article) (*model.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertArticle", arg0, arg1)
	ret0, _ := ret[0].(*model.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertArticle indicates an expected call of InsertArticle.
func (mr *MockArticleMockRecorder) InsertArticle(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertArticle", reflect.TypeOf((*MockArticle)(nil).InsertArticle), arg0, arg1)
}
